// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlGen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Player struct {
	PlayerID  int64              `json:"player_id"`
	Name      string             `json:"name"`
	EosID     string             `json:"eos_id"`
	SteamID   string             `json:"steam_id"`
	FirstSeen pgtype.Timestamptz `json:"first_seen"`
	LastSeen  pgtype.Timestamptz `json:"last_seen"`
}

type SchemaMigration struct {
	Version string `json:"version"`
}
